### ISSUE TITLE
Downloaded Version does not match checksum

### ISSUE THREAD

**Issue by cbm-afettach** [rhyeal/aws-rotate-iam-keys#31] opened 2020-01-30 14:23 UTC
https://github.com/rhyeal/aws-rotate-iam-keys/blob/11761486c3ffceb76741c134e05814fc9db5f34d/Formula/aws-rotate-iam-keys.rb#L4

Hello we're having a problem to install the tool (v0.9.5) since it seems to download a previous version v0.9.2 which fails the checksum verification : 
The version is hard-coded and should be rather referenced with a variable: 
```
==> Downloading https://github.com/rhyeal/aws-rotate-iam-keys/archive/v0.9.2.tar.gz
Already downloaded: /Users/anasfettach/Library/Caches/Homebrew/downloads/ac8e0f9303ae07d8bec762733bb3# corporate account
57796a5236df656317a779653bcaec640429--aws-rotate-iam-keys-0.9.2.tar.gz
Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: ccbd38ba4c8725438961b0e9a23a5c713b91568e9ebe6f3b687246140b82f89c
  Actual: 9101bff2a889e5c883fda99b12588dd50bee9d42faf77f6d6e5d94ab35abb9e1
 Archive: /Users/anasfettach/Library/Caches/Homebrew/downloads/ac8e0f9303ae07d8bec762733bb357796a5236df656317a779653bcaec640429--aws-rotate-iam-keys-0.9.2.tar.gz
To retry an incomplete download, remove the file above.
```
Regards

**Comment by jasoniangreen** [comment] 2020-01-30 15:01
Duplicate of #29

**Comment by mmrwoods** [comment] 2020-03-05 09:46
@cbm-afettach Use `brew install aws-rotate-iam-keys --HEAD` for now, see #29 for more info

**Comment by rhyeal** [comment] 2020-03-23 19:29
Closing this out as the new CI/CD process will publish the correct SHA256 now automatically.

**Closed as completed by rhyeal** 2020-03-23 19:29 UTC
